### ISSUE TITLE
INT Pin

### ISSUE THREAD

**Issue by star210** [RoelKroes/WSPR_HAB_tracker#2]
Hi Roel

Few questions no issues.

Just checking the VTCXO wire which connects to the TCXO vcc pin is the power from the atmega328. From what I can work out the code interrupts the power to the oscillator to produce the final waveform? 

Also I cant find any 27mhz TCXOs on JLC will 26mhz be ok, I see that we can enter the TCXO Freq in the code?

Star

**Comment by RoelKroes** [comment]
1) Forget about the VTCXO wire. Somehow this wire is still on the schematic...Sorry about that. Just connect that pin of the TCXO to VCC with a 10nF cap to GND.

2) Maybe aliexpress? If I remember correctly, I bought those there. I also tried 26MHz. It might work but I had trouble with the GPS getting a fix. Probably because of a design error in the PCB. But I do not have the knowledge to debug these kind of RF issues. There are 3 oscillators present within the space of a few square cm's. With my knowledge it is more or less trial and error!

Roel.

**Comment by star210** [comment]
No problem I just couldnt see any reference to it anywhere on the net :)
Ill let you know how my PCB turns out
Star

**Comment by RoelKroes** [comment]
Great!

Roel.
